package org.firstinspires.ftc.teamcode.opmodes;

import com.pedropathing.follower.Follower;
import com.pedropathing.geometry.BezierLine;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathChain;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

/**
 * Mark2 — Blue Initial Autonomous
 *
 * Alliance:  BLUE
 * Start:     (19.45, 119.62) facing 90° — matches startPoint in Mark2BlueInitialAuto.pp
 *
 * Path summary (derived from Mark2BlueInitialAuto.pp)
 * ────────────────────────────────────────────────────
 *  1.  Drive to FireLocation                              → shoot preloads
 *  2.  Intake sweep — middle floor (IntakeFloorMiddle)    → intake on during drive
 *  3.  Return to FireLocation                             → shoot middle-floor pickup
 *  4–11. Four gate-load cycles (FireLocation ↔ GateLoad) → intake on inbound,
 *                                                            reverse-clear + shoot on return
 * 12.  Intake sweep — close floor (IntakeFloorClose)     → intake on during drive
 * 13.  Drive to FinalFirePosition                        → shoot close-floor pickup
 *
 * Navigation uses the Mark2AutoBase Pinpoint PID (navigate / navigateWithIntake).
 * The Paths inner class uses Pedro Pathing path-following and is included for
 * future migration; it is not called by runPath() in this OpMode.
 *
 * Tuning checklist:
 *   LAUNCH_DISTANCE_MAIN  — measure FireLocation → goal (inches)
 *   LAUNCH_DISTANCE_FINAL — measure FinalFirePosition → goal (inches)
 *   OUTTAKE_REVERSE_S     — inherited from Mark2AutoBase
 */
@Autonomous(name = "Mark2 Blue Initial Auto", group = "Mark2")
public class Mark2BlueInitialAuto extends Mark2AutoBase {

    // ── Starting pose — matches startPoint in Mark2BlueInitialAuto.pp ─────────
    private static final double START_X   = 19.450;
    private static final double START_Y   = 119.623;
    private static final double START_ROT = 90.0;    // degrees — pp startPoint.startDeg

    // ── Launch distances (inches) — TUNE to actual measured goal distances ─────
    private static final double LAUNCH_DISTANCE_MAIN  = 48.0; // TUNE
    private static final double LAUNCH_DISTANCE_FINAL = 36.0; // TUNE

    // =========================================================================
    // >>>  JAVAFRAGMENT PASTE SECTION — START  <<<
    //
    //  Generated by : Scripts\Convert-PedroToJavaPoints.ps1
    //  Source file  : Scripts\Mark2BlueInitialAuto.pp
    //  Fragment file: Scripts\InputAndOutput\Mark2BlueInitialAuto_points.javafragment
    //
    //  HOW TO UPDATE when paths change:
    //    1. Export updated paths from the Pedro visualizer to
    //         Scripts\Mark2BlueInitialAuto.pp
    //       OR re-generate from Java using Convert-JavaToPedroPp.ps1.
    //    2. Run from the Scripts\ directory:
    //         .\Convert-PedroToJavaPoints.ps1 .\Mark2BlueInitialAuto.pp
    //    3. Open Scripts\InputAndOutput\Mark2BlueInitialAuto_points.javafragment
    //    4. Select all and paste, replacing everything between START and END.
    // =========================================================================

    private static final Pose STARTINGPOSITION_POSE = new Pose(19.450, 119.623, Math.toRadians(323.000));
    private static final Pose FIRELOCATION_POSE = new Pose(55.393, 85.593, Math.toRadians(310.000));
    private static final Pose INTAKEFLOORMIDDLE_POSE = new Pose(22.913, 58.959, Math.toRadians(310.000));
    private static final Pose INTAKEFLOORMIDDLE_POSE_2 = new Pose(22.913, 58.959, Math.toRadians(180.000));
    private static final Pose FIRELOCATION_POSE_2 = new Pose(55.238, 85.504, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE = new Pose(13.642, 59.503, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_2 = new Pose(13.642, 59.503, Math.toRadians(155.000));
    private static final Pose FIRELOCATION_POSE_3 = new Pose(55.492, 85.180, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_3 = new Pose(13.656, 59.517, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_4 = new Pose(13.656, 59.517, Math.toRadians(155.000));
    private static final Pose FIRELOCATION_POSE_4 = new Pose(55.333, 85.523, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_5 = new Pose(13.693, 59.558, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_6 = new Pose(13.693, 59.558, Math.toRadians(155.000));
    private static final Pose FIRELOCATION_POSE_5 = new Pose(55.297, 85.502, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_7 = new Pose(13.833, 59.559, Math.toRadians(220.000));
    private static final Pose GATELOAD_POSE_8 = new Pose(13.833, 59.559, Math.toRadians(155.000));
    private static final Pose FIRELOCATION_POSE_6 = new Pose(55.436, 85.618, Math.toRadians(220.000));
    private static final Pose FIRELOCATION_POSE_7 = new Pose(55.436, 85.618, Math.toRadians(180.000));
    private static final Pose INTAKEFLOORCLOSE_POSE = new Pose(23.797, 83.290, Math.toRadians(180.000));
    private static final Pose FINALFIREPOSITION_POSE = new Pose(56.682, 103.156, Math.toRadians(220.000));

    public static class Paths {
        public PathChain startingpositionToFirelocation;
        public PathChain firelocationToIntakefloormiddle;
        public PathChain intakefloormiddlePose2ToFirelocationPose2;
        public PathChain firelocationPose2ToGateload;
        public PathChain gateloadPose2ToFirelocationPose3;
        public PathChain firelocationPose3ToGateloadPose3;
        public PathChain gateloadPose4ToFirelocationPose4;
        public PathChain firelocationPose4ToGateloadPose5;
        public PathChain gateloadPose6ToFirelocationPose5;
        public PathChain firelocationPose5ToGateloadPose7;
        public PathChain gateloadPose8ToFirelocationPose6;
        public PathChain firelocationPose7ToIntakefloorclose;
        public PathChain intakefloorcloseToFinalfireposition;

        public Paths(Follower follower) {
            // StartingPosition to FireLocation
            startingpositionToFirelocation = follower
                    .pathBuilder()
                    .addPath(new BezierLine(STARTINGPOSITION_POSE, FIRELOCATION_POSE))
                    .setLinearHeadingInterpolation(STARTINGPOSITION_POSE.getHeading(), FIRELOCATION_POSE.getHeading())
                    .build();

            // FIreLocation to IntakeFloorMiddle
            firelocationToIntakefloormiddle = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE, INTAKEFLOORMIDDLE_POSE))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE.getHeading(), INTAKEFLOORMIDDLE_POSE.getHeading())
                    .build();

            // IntakeFloorMiddle to FireLocation
            intakefloormiddlePose2ToFirelocationPose2 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(INTAKEFLOORMIDDLE_POSE_2, FIRELOCATION_POSE_2))
                    .setLinearHeadingInterpolation(INTAKEFLOORMIDDLE_POSE_2.getHeading(), FIRELOCATION_POSE_2.getHeading())
                    .build();

            // FIreLocation to GateLoad
            firelocationPose2ToGateload = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE_2, GATELOAD_POSE))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE_2.getHeading(), GATELOAD_POSE.getHeading())
                    .build();

            // GateLoad to FireLocation
            gateloadPose2ToFirelocationPose3 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(GATELOAD_POSE_2, FIRELOCATION_POSE_3))
                    .setLinearHeadingInterpolation(GATELOAD_POSE_2.getHeading(), FIRELOCATION_POSE_3.getHeading())
                    .build();

            // FireLocation to GateLoad
            firelocationPose3ToGateloadPose3 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE_3, GATELOAD_POSE_3))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE_3.getHeading(), GATELOAD_POSE_3.getHeading())
                    .build();

            // GateLoad to FireLocation
            gateloadPose4ToFirelocationPose4 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(GATELOAD_POSE_4, FIRELOCATION_POSE_4))
                    .setLinearHeadingInterpolation(GATELOAD_POSE_4.getHeading(), FIRELOCATION_POSE_4.getHeading())
                    .build();

            // FireLocation to GateLoad
            firelocationPose4ToGateloadPose5 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE_4, GATELOAD_POSE_5))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE_4.getHeading(), GATELOAD_POSE_5.getHeading())
                    .build();

            // GateLoad to FireLocation
            gateloadPose6ToFirelocationPose5 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(GATELOAD_POSE_6, FIRELOCATION_POSE_5))
                    .setLinearHeadingInterpolation(GATELOAD_POSE_6.getHeading(), FIRELOCATION_POSE_5.getHeading())
                    .build();

            // FireLocation to GateLoad
            firelocationPose5ToGateloadPose7 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE_5, GATELOAD_POSE_7))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE_5.getHeading(), GATELOAD_POSE_7.getHeading())
                    .build();

            // GateLoad to FireLocation
            gateloadPose8ToFirelocationPose6 = follower
                    .pathBuilder()
                    .addPath(new BezierLine(GATELOAD_POSE_8, FIRELOCATION_POSE_6))
                    .setLinearHeadingInterpolation(GATELOAD_POSE_8.getHeading(), FIRELOCATION_POSE_6.getHeading())
                    .build();

            // FIreLocation to IntakeFloorClose
            firelocationPose7ToIntakefloorclose = follower
                    .pathBuilder()
                    .addPath(new BezierLine(FIRELOCATION_POSE_7, INTAKEFLOORCLOSE_POSE))
                    .setLinearHeadingInterpolation(FIRELOCATION_POSE_7.getHeading(), INTAKEFLOORCLOSE_POSE.getHeading())
                    .build();

            // IntakeFloorClose to FinalFirePosition
            intakefloorcloseToFinalfireposition = follower
                    .pathBuilder()
                    .addPath(new BezierLine(INTAKEFLOORCLOSE_POSE, FINALFIREPOSITION_POSE))
                    .setLinearHeadingInterpolation(INTAKEFLOORCLOSE_POSE.getHeading(), FINALFIREPOSITION_POSE.getHeading())
                    .build();

        }
    }

    // =========================================================================
    // >>>  JAVAFRAGMENT PASTE SECTION — END  <<<
    // =========================================================================

    // =========================================================================
    // Subsystem init
    // =========================================================================

    @Override
    protected void setup() {
        initSubsystems(START_X, START_Y, START_ROT);

        telemetry.addLine("Mark2 Blue Initial Auto — Ready");
        telemetry.addData("Start pose",
                String.format("(%.2f, %.2f)  %.0f deg", START_X, START_Y, START_ROT));
        telemetry.addData("Launch dist main  (in)", LAUNCH_DISTANCE_MAIN);
        telemetry.addData("Launch dist final (in)", LAUNCH_DISTANCE_FINAL);
        telemetry.update();
    }

    // =========================================================================
    // Autonomous path sequence
    // =========================================================================

    @Override
    protected void runPath() {

        // ── 1. Drive to initial fire position ──────────────────────────────────
        //   Robot drives to FireLocation and shoots preloaded game elements.
        currentPhase = "Drive to FireLocation (preloads)";
        navigate(FIRELOCATION_POSE);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // ── 2. Intake sweep — middle floor ─────────────────────────────────────
        //   Intake spins up while driving to IntakeFloorMiddle to collect
        //   game elements along the tangential sweep path.
        currentPhase = "Intake sweep - middle floor";
        navigateWithIntake(INTAKEFLOORMIDDLE_POSE);

        // Briefly run intake in reverse while driving back to clear any
        // misaligned elements before the feeder sequence.
        startReverseFor(OUTTAKE_REVERSE_S);

        // ── 3. Return to fire — middle-floor pickup ────────────────────────────
        currentPhase = "Return to fire (cycle 1)";
        navigate(FIRELOCATION_POSE_2);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // ── 4–11. Gate-load cycles ─────────────────────────────────────────────
        //   Four trips to GateLoad to collect additional game elements.
        //   Intake is active on every inbound (to-gate) leg.
        //   startReverseFor() clears the intake path concurrently with the
        //   return drive leg (timer ticks inside navigate()).

        // Gate cycle 1
        currentPhase = "Gate cycle 1 - collect";
        navigateWithIntake(GATELOAD_POSE);
        startReverseFor(OUTTAKE_REVERSE_S);
        currentPhase = "Gate cycle 1 - fire";
        navigate(FIRELOCATION_POSE_3);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // Gate cycle 2
        currentPhase = "Gate cycle 2 - collect";
        navigateWithIntake(GATELOAD_POSE_3);
        startReverseFor(OUTTAKE_REVERSE_S);
        currentPhase = "Gate cycle 2 - fire";
        navigate(FIRELOCATION_POSE_4);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // Gate cycle 3
        currentPhase = "Gate cycle 3 - collect";
        navigateWithIntake(GATELOAD_POSE_5);
        startReverseFor(OUTTAKE_REVERSE_S);
        currentPhase = "Gate cycle 3 - fire";
        navigate(FIRELOCATION_POSE_5);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // Gate cycle 4
        currentPhase = "Gate cycle 4 - collect";
        navigateWithIntake(GATELOAD_POSE_7);
        startReverseFor(OUTTAKE_REVERSE_S);
        currentPhase = "Gate cycle 4 - fire";
        navigate(FIRELOCATION_POSE_6);
        shootFrom(LAUNCH_DISTANCE_MAIN);

        // ── 12. Intake sweep — close floor ─────────────────────────────────────
        //   Short linear sweep picks up game elements near the close wall.
        currentPhase = "Intake sweep - close floor";
        navigateWithIntake(INTAKEFLOORCLOSE_POSE);
        startReverseFor(OUTTAKE_REVERSE_S);

        // ── 13. Final fire position ────────────────────────────────────────────
        currentPhase = "Final fire position";
        navigate(FINALFIREPOSITION_POSE);
        shootFrom(LAUNCH_DISTANCE_FINAL);

        currentPhase = "Done";
        postTelemetry();
    }

    // =========================================================================
    // Pose-based navigation helpers
    // =========================================================================

    /** Navigate to a Pedro Pathing {@link Pose}; heading converted radians → degrees. */
    private void navigate(Pose pose) {
        navigate(pose.getX(), pose.getY(), Math.toDegrees(pose.getHeading()));
    }

    /** Navigate to a Pedro Pathing {@link Pose} with the intake running. */
    private void navigateWithIntake(Pose pose) {
        navigateWithIntake(pose.getX(), pose.getY(), Math.toDegrees(pose.getHeading()));
    }
}
